import {createHash} from 'node:crypto';
import {cp, mkdir, readFile, writeFile, rm} from 'node:fs/promises';
import {join} from 'node:path';
const root = new URL('../', import.meta.url).pathname;
const output = join(root, 'assets/processor');
// This directory contains generated assets only. Keep deployments free of
// obsolete model/runtime versions after dependencies or weights change.
await rm(output, {recursive: true, force: true});
await mkdir(output, {recursive: true});
const ortPackage = JSON.parse(await readFile(join(root, 'node_modules/onnxruntime-web/package.json'), 'utf8'));
const runtime = `/assets/processor/ort-${ortPackage.version}`;
await mkdir(join(root, runtime), {recursive: true});
for (const name of ['ort.webgpu.min.mjs', 'ort.wasm.min.mjs',
  'ort-wasm-simd-threaded.asyncify.mjs', 'ort-wasm-simd-threaded.asyncify.wasm',
  'ort-wasm-simd-threaded.mjs', 'ort-wasm-simd-threaded.wasm']) {
  await cp(join(root, 'node_modules/onnxruntime-web/dist', name), join(root, runtime, name));
}
const assets = {runtime};
for (const [key, file] of [['modelGpu', 'normal_2x_web.onnx'], ['modelCpu', 'normal_2x_web.ort']]) {
  let bytes;
  try { bytes = await readFile(join(root, 'static/models', file)); }
  catch { throw new Error(`Missing ${file}. Restore the approved model artifacts described in BROWSER_IMAGE_PROCESSING.md before building the preview.`); }
  const hash = createHash('sha256').update(bytes).digest('hex').slice(0,16);
  assets[key] = `/assets/processor/${hash}-${file}`;
  await writeFile(join(root, assets[key]), bytes);
}
// Pages serves files up to 25 MiB. Reassemble the exact face model in the worker.
const faceBytes = await readFile(join(root, 'static/models/face_512.onnx'));
assets.faceModel = {bytes: faceBytes.length, parts: []};
for (let offset = 0; offset < faceBytes.length; offset += 20 * 1024 * 1024) {
  const part = faceBytes.subarray(offset, offset + 20 * 1024 * 1024);
  const hash = createHash('sha256').update(part).digest('hex').slice(0,16);
  const url = `/assets/processor/face-${hash}.bin`;
  await writeFile(join(root, url), part);
  assets.faceModel.parts.push({url, bytes: part.length});
}
const visionPackage = JSON.parse(await readFile(join(root, 'node_modules/@mediapipe/tasks-vision/package.json'), 'utf8'));
assets.vision = `/assets/processor/vision-${visionPackage.version}`;
await mkdir(join(root, assets.vision), {recursive: true});
await cp(join(root, 'node_modules/@mediapipe/tasks-vision/vision_bundle.mjs'), join(root, assets.vision, 'vision_bundle.mjs'));
await cp(join(root, 'node_modules/@mediapipe/tasks-vision/wasm'), join(root, assets.vision, 'wasm'), {recursive: true});
const detector = await readFile(join(root, 'static/models/face_landmarker.task'));
assets.faceDetector = `/assets/processor/${createHash('sha256').update(detector).digest('hex').slice(0,16)}-face_landmarker.task`;
await writeFile(join(root, assets.faceDetector), detector);
await writeFile(join(root, 'src/tool/assets.generated.js'), `// Generated by prepare_tool_assets.mjs.\nexport const ASSETS = ${JSON.stringify(assets, null, 2)};\n`);
console.log('Prepared versioned photo models and browser runtime.');
