import {createHash} from 'node:crypto';
import {cp, mkdir, readFile, writeFile, rm} from 'node:fs/promises';
import {join} from 'node:path';
const root = new URL('../', import.meta.url).pathname;
const output = join(root, 'assets/processor');
// This directory contains generated assets only. Keep deployments free of
// obsolete model/runtime versions after dependencies or weights change.
await rm(output, {recursive: true, force: true});
await mkdir(output, {recursive: true});
const ortPackage = JSON.parse(await readFile(join(root, 'node_modules/onnxruntime-web/package.json'), 'utf8'));
const runtime = `/assets/processor/ort-${ortPackage.version}`;
await mkdir(join(root, runtime), {recursive: true});
for (const name of ['ort.webgpu.min.mjs', 'ort.wasm.min.mjs',
  'ort-wasm-simd-threaded.asyncify.mjs', 'ort-wasm-simd-threaded.asyncify.wasm',
  'ort-wasm-simd-threaded.mjs', 'ort-wasm-simd-threaded.wasm']) {
  await cp(join(root, 'node_modules/onnxruntime-web/dist', name), join(root, runtime, name));
}
const assets = {runtime};
for (const [key, file] of [['modelGpu', 'normal_2x_web.onnx'], ['modelCpu', 'normal_2x_web.ort']]) {
  let bytes;
  try { bytes = await readFile(join(root, 'static/models', file)); }
  catch { throw new Error(`Missing ${file}. Restore the approved model artifacts described in BROWSER_IMAGE_PROCESSING.md before building the preview.`); }
  const hash = createHash('sha256').update(bytes).digest('hex').slice(0,16);
  assets[key] = `/assets/processor/${hash}-${file}`;
  await writeFile(join(root, assets[key]), bytes);
}
await writeFile(join(root, 'src/tool/assets.generated.js'), `// Generated by prepare_tool_assets.mjs.\nexport const ASSETS = ${JSON.stringify(assets, null, 2)};\n`);
console.log('Prepared versioned photo models and browser runtime.');
