import {createHash} from 'node:crypto';
import {cp, mkdir, readFile, writeFile, rm} from 'node:fs/promises';
import {join} from 'node:path';
const root = new URL('../', import.meta.url).pathname;
const output = join(root, 'assets/processor');
const modelSpecs = [];
for (const [modelKind, prefix] of [['photo', 'normal'], ['drawing', 'anime']]) {
  for (const scale of [2, 4]) {
    for (const [key, file] of [['gpu', `${prefix}_${scale}x_web.onnx`], ['cpu', `${prefix}_${scale}x_web.ort`]]) {
      modelSpecs.push({modelKind, scale, key, file});
    }
  }
}

// Validate every source before replacing the last usable package. A missing
// drawing artifact must never erase already working photo assets.
const modelBytes = new Map();
for (const {file} of modelSpecs) {
  try { modelBytes.set(file, await readFile(join(root, 'static/models', file))); }
  catch {
    throw new Error(`Missing ${file}. Restore the approved photo and drawing model artifacts described in BROWSER_IMAGE_PROCESSING.md before building the preview.`);
  }
}
const finder = await readFile(join(root, 'static/models/face_detector_yunet.onnx'));
const detector = await readFile(join(root, 'static/models/face_landmarker.task'));
// This directory contains generated assets only. Keep deployments free of
// obsolete model/runtime versions after dependencies or weights change.
await rm(output, {recursive: true, force: true});
await mkdir(output, {recursive: true});
const ortPackage = JSON.parse(await readFile(join(root, 'node_modules/onnxruntime-web/package.json'), 'utf8'));
const runtime = `/assets/processor/ort-${ortPackage.version}`;
await mkdir(join(root, runtime), {recursive: true});
for (const name of ['ort.webgpu.min.mjs', 'ort.wasm.min.mjs',
  'ort-wasm-simd-threaded.asyncify.mjs', 'ort-wasm-simd-threaded.asyncify.wasm',
  'ort-wasm-simd-threaded.mjs', 'ort-wasm-simd-threaded.wasm']) {
  await cp(join(root, 'node_modules/onnxruntime-web/dist', name), join(root, runtime, name));
}
const assets = {runtime, models: {photo: {}, drawing: {}}};
for (const {modelKind, scale, key, file} of modelSpecs) {
  assets.models[modelKind][scale] ||= {};
  const bytes = modelBytes.get(file);
  const hash = createHash('sha256').update(bytes).digest('hex').slice(0,16);
  assets.models[modelKind][scale][key] = `/assets/processor/${hash}-${file}`;
  await writeFile(join(root, assets.models[modelKind][scale][key]), bytes);
}
// The 85 MB face model is over the per-file limit for site assets, so it lives in
// the aura-lens-models R2 bucket beside the app models and downloads from
// upscales.uk (the bucket's CORS rule allows this site's origins). face-model.json
// pins the exact object by content hash: when the weights change, upload the new
// file under its new hash and update that file. The build no longer needs the
// model locally. One part keeps runtime.js's streaming loader unchanged.
const faceModel = JSON.parse(await readFile(join(root, 'src/tool/face-model.json'), 'utf8'));
assets.faceModel = {bytes: faceModel.bytes, parts: [{url: faceModel.url, bytes: faceModel.bytes}]};
const visionPackage = JSON.parse(await readFile(join(root, 'node_modules/@mediapipe/tasks-vision/package.json'), 'utf8'));
assets.vision = `/assets/processor/vision-${visionPackage.version}`;
await mkdir(join(root, assets.vision), {recursive: true});
await cp(join(root, 'node_modules/@mediapipe/tasks-vision/vision_bundle.mjs'), join(root, assets.vision, 'vision_bundle.mjs'));
await cp(join(root, 'node_modules/@mediapipe/tasks-vision/wasm'), join(root, assets.vision, 'wasm'), {recursive: true});
assets.faceFinder = `/assets/processor/${createHash('sha256').update(finder).digest('hex').slice(0,16)}-face_detector_yunet.onnx`;
await writeFile(join(root, assets.faceFinder), finder);
assets.faceDetector = `/assets/processor/${createHash('sha256').update(detector).digest('hex').slice(0,16)}-face_landmarker.task`;
await writeFile(join(root, assets.faceDetector), detector);
await writeFile(join(root, 'src/tool/assets.generated.js'), `// Generated by prepare_tool_assets.mjs.\nexport const ASSETS = ${JSON.stringify(assets, null, 2)};\n`);
console.log('Prepared versioned photo models and browser runtime.');
